import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://zdgycrygjlvvlbnuslfx.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZ3ljcnlnamx2dmxibnVzbGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMDY2NDksImV4cCI6MjA0OTU4MjY0OX0.MzoPS5NLIMFv23rzCmuA05dhYkyMHeU3QgHniI1Xdk8')